series: Matrix Mathematics
title: Matrix rotation
author:
  name: Andrew Litfin
  email:
  github: astrodude80
description: This tutorial explores rotation matrices.
language: C++
tags:
  - Math
extra_resources:
connections:
  - series: Matrix Mathematics
    title: Matrices and Vectors
