series: Matrix Mathematics
title: Matrix Rotation
author:
  name: Andrew Litfin
  email:
  github: astrodude80
description: This tutorial explores rotation matrices.
language: C++
tags:
  - Math
extra_resources:
  - title: The Wikipedia article on rotation matrices
    link: https://en.wikipedia.org/wiki/Rotation_matrix
connections:
  - series: Matrix Mathematics
    title: Matrices and Vectors
